Добавляет карту в список предложений
htmlacademy-react/175289-six-cities-7 pull request #6
Opened 2021-07-07 06:49 UTC by yuliasitnikova

2021-07-08 03:59 UTC, Razzwan requested changes

2021-07-08 03:59 UTC, Razzwan commented on project/package.json
> +    "leaflet": "^1.7.1",
Версии пакетов должны быть без птичек в начале. Это для того, чтоб случайно не сломать работающий код после автоматического обновления

2021-07-08 03:59 UTC, Razzwan commented on project/src/components/places-item/places-item.jsx
> +    <article className="cities__place-card place-card" onMouseEnter={(evt) => {onHover(id);}}>
Про анонимные функции надо поговорить

2021-07-08 03:59 UTC, Razzwan commented on project/src/components/places-item/places-item.jsx
> +          <button className={`place-card__bookmark-button ${isFavorite && 'place-card__bookmark-button--active'} button`} type="button">
Есть библиотека для задач формирования классов на основе переменных: `classnames`

2021-07-08 03:59 UTC, Razzwan commented on project/src/components/places-map/places-map.jsx
> +      <div style={{'height': '100%'}} ref={mapRef}></div>
Закрывающий тег не нужен:
```jsx
<div style={{'height': '100%'}} ref={mapRef} />
```

2021-07-08 03:59 UTC, Razzwan commented on project/src/components/places/places.jsx
> +  const onItemHover = (itemId) => {
Поговорить об анонимных функциях

2021-07-08 03:59 UTC, Razzwan commented on project/src/hooks/useMap/useMap.js
> +function useMap(mapRef, city) {
Здорово! Можно еще больше кода здесь разместить, относящегося к формированию карты

2021-07-08 09:35 UTC, yuliasitnikova commented on project/src/components/places-map/places-map.jsx
> +      <div style={{'height': '100%'}} ref={mapRef}></div>
@Razzwan получается, все пустые теги нужно писать без закрывающего тега?

2021-07-08 09:36 UTC, yuliasitnikova commented on project/package.json
> +    "leaflet": "^1.7.1",
@Razzwan, нужно, чтобы было просто "leaflet": "1.7.1"?

2021-07-08 17:24 UTC, yuliasitnikova commented on project/package.json
> +    "leaflet": "^1.7.1",
Исправлено

2021-07-08 17:25 UTC, yuliasitnikova commented on project/src/components/places-item/places-item.jsx
> +    <article className="cities__place-card place-card" onMouseEnter={(evt) => {onHover(id);}}>
Исправлено

2021-07-08 17:25 UTC, yuliasitnikova commented on project/src/components/places-item/places-item.jsx
> +          <button className={`place-card__bookmark-button ${isFavorite && 'place-card__bookmark-button--active'} button`} type="button">
Подключила, исправила

2021-07-08 17:25 UTC, yuliasitnikova commented on project/src/components/places-map/places-map.jsx
> +      <div style={{'height': '100%'}} ref={mapRef}></div>
Исправлено

2021-07-08 17:25 UTC, yuliasitnikova commented on project/src/hooks/useMap/useMap.js
> +function useMap(mapRef, city) {
Пока оставила так до работы в картой на внутренней странице

2021-07-10 16:11 UTC, Razzwan approved these changes

2021-07-10 16:11 UTC, Razzwan commented on project/src/components/favorites-list/favorites-list.jsx
> +      {Object.keys(favoritesObject).map((item) => (
Здесь item лучше сменить на более информативное: `cityName`

2021-07-10 16:11 UTC, merged